"""baseline: full schema as of 2026-07-17

Revision ID: 974cc2004deb
Revises: 
Create Date: 2026-07-17 22:43:24.557703
"""
from alembic import op
import sqlalchemy as sa


revision = '974cc2004deb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_month'), 'api_usage', ['month'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('template_code', sa.String(length=20), nullable=True),
    sa.Column('bse_scrip_code', sa.String(length=20), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_bse_scrip_code'), 'companies', ['bse_scrip_code'], unique=False)
    op.create_index(op.f('ix_companies_template_code'), 'companies', ['template_code'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('engine_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('conviction', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('val_blend', sa.Float(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('suspect', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'ticker', name='uq_engine_call')
    )
    op.create_index(op.f('ix_engine_calls_date'), 'engine_calls', ['date'], unique=False)
    op.create_index(op.f('ix_engine_calls_ticker'), 'engine_calls', ['ticker'], unique=False)
    op.create_table('kv_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kv_store_key'), 'kv_store', ['key'], unique=True)
    op.create_table('saved_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_key', 'ticker', 'name', name='uq_scenario')
    )
    op.create_index(op.f('ix_saved_scenarios_ticker'), 'saved_scenarios', ['ticker'], unique=False)
    op.create_index(op.f('ix_saved_scenarios_user_key'), 'saved_scenarios', ['user_key'], unique=False)
    op.create_table('saved_screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_key', 'name', name='uq_screen')
    )
    op.create_index(op.f('ix_saved_screens_user_key'), 'saved_screens', ['user_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alpha_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('alpha_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('low_vol', sa.Float(), nullable=True),
    sa.Column('growth', sa.Float(), nullable=True),
    sa.Column('catalyst', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_alpha_company_date')
    )
    op.create_index(op.f('ix_alpha_snapshots_company_id'), 'alpha_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_alpha_snapshots_date'), 'alpha_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_alpha_snapshots_ticker'), 'alpha_snapshots', ['ticker'], unique=False)
    op.create_table('assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('risk_free', sa.Float(), nullable=True),
    sa.Column('erp', sa.Float(), nullable=True),
    sa.Column('forecast_roe', sa.Float(), nullable=True),
    sa.Column('terminal_roe', sa.Float(), nullable=True),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.Column('rev_growth', sa.Float(), nullable=True),
    sa.Column('ebit_margin', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('reinvest_rate', sa.Float(), nullable=True),
    sa.Column('debt_weight', sa.Float(), nullable=True),
    sa.Column('cost_debt', sa.Float(), nullable=True),
    sa.Column('fade_years', sa.Float(), nullable=True),
    sa.Column('terminal_growth', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('auth_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_events_email'), 'auth_events', ['email'], unique=False)
    op.create_index(op.f('ix_auth_events_user_id'), 'auth_events', ['user_id'], unique=False)
    op.create_table('company_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_insights_company_id'), 'company_insights', ['company_id'], unique=True)
    op.create_table('consensus_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('target', sa.Float(), nullable=True),
    sa.Column('upside', sa.Float(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.Column('num_analysts', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_consensus_company_date')
    )
    op.create_index(op.f('ix_consensus_snapshots_company_id'), 'consensus_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_consensus_snapshots_date'), 'consensus_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_consensus_snapshots_ticker'), 'consensus_snapshots', ['ticker'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=12), nullable=False),
    sa.Column('ex_date', sa.String(length=10), nullable=True),
    sa.Column('record_date', sa.String(length=10), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('raw_remarks', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'action_type', 'ex_date', 'value', name='uq_corp_action')
    )
    op.create_index(op.f('ix_corporate_actions_company_id'), 'corporate_actions', ['company_id'], unique=False)
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'period', 'concept', name='uq_fact')
    )
    op.create_index(op.f('ix_financial_facts_company_id'), 'financial_facts', ['company_id'], unique=False)
    op.create_table('historical_financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.String(), nullable=False),
    sa.Column('line_item', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'statement_type', 'line_item', name='uq_hist_fin')
    )
    op.create_index(op.f('ix_historical_financials_company_id'), 'historical_financials', ['company_id'], unique=False)
    op.create_table('historical_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_hist_price')
    )
    op.create_index(op.f('ix_historical_prices_company_id'), 'historical_prices', ['company_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('as_of', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_key', 'company_id', name='uq_portfolio_user_company')
    )
    op.create_index(op.f('ix_portfolio_holdings_company_id'), 'portfolio_holdings', ['company_id'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_user_key'), 'portfolio_holdings', ['user_key'], unique=False)
    op.create_table('price_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Integer(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_points_company_id'), 'price_points', ['company_id'], unique=False)
    op.create_table('quarterly_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('bse_announcement_id', sa.String(length=100), nullable=True),
    sa.Column('bse_filing_date', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('r2_key', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'quarter', 'doc_type', name='uq_qd_company_quarter_type')
    )
    op.create_index(op.f('ix_quarterly_documents_company_id'), 'quarterly_documents', ['company_id'], unique=False)
    op.create_table('transcript_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('quarter', sa.String(length=24), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('tone_score', sa.Float(), nullable=True),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('llm_summary', sa.String(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_insights_company_id'), 'transcript_insights', ['company_id'], unique=True)
    op.create_index(op.f('ix_transcript_insights_ticker'), 'transcript_insights', ['ticker'], unique=False)
    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('intrinsic', sa.Float(), nullable=True),
    sa.Column('mos', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('composite', sa.Float(), nullable=True),
    sa.Column('reliable', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('valuation_sector', sa.String(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('analyst_target', sa.Float(), nullable=True),
    sa.Column('analyst_low', sa.Float(), nullable=True),
    sa.Column('analyst_high', sa.Float(), nullable=True),
    sa.Column('analyst_rating', sa.String(), nullable=True),
    sa.Column('analyst_upside', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_company_id'), 'valuations', ['company_id'], unique=True)
    op.create_table('verdict_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('intrinsic', sa.Float(), nullable=True),
    sa.Column('mos', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('composite', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('valuation_sector', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_snapshot_company_date')
    )
    op.create_index(op.f('ix_verdict_snapshots_company_id'), 'verdict_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_verdict_snapshots_date'), 'verdict_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_verdict_snapshots_ticker'), 'verdict_snapshots', ['ticker'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('mos_threshold', sa.Float(), nullable=True),
    sa.Column('move_threshold', sa.Float(), nullable=True),
    sa.Column('alert_verdict', sa.Integer(), nullable=False),
    sa.Column('alert_mos', sa.Integer(), nullable=False),
    sa.Column('alert_target', sa.Integer(), nullable=False),
    sa.Column('alert_move', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('last_verdict', sa.String(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_key', 'company_id', name='uq_watch_user_company')
    )
    op.create_index(op.f('ix_watchlist_items_company_id'), 'watchlist_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_key'), 'watchlist_items', ['user_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_user_key'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_company_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_verdict_snapshots_ticker'), table_name='verdict_snapshots')
    op.drop_index(op.f('ix_verdict_snapshots_date'), table_name='verdict_snapshots')
    op.drop_index(op.f('ix_verdict_snapshots_company_id'), table_name='verdict_snapshots')
    op.drop_table('verdict_snapshots')
    op.drop_index(op.f('ix_valuations_company_id'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_index(op.f('ix_transcript_insights_ticker'), table_name='transcript_insights')
    op.drop_index(op.f('ix_transcript_insights_company_id'), table_name='transcript_insights')
    op.drop_table('transcript_insights')
    op.drop_index(op.f('ix_quarterly_documents_company_id'), table_name='quarterly_documents')
    op.drop_table('quarterly_documents')
    op.drop_index(op.f('ix_price_points_company_id'), table_name='price_points')
    op.drop_table('price_points')
    op.drop_index(op.f('ix_portfolio_holdings_user_key'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_company_id'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_historical_prices_company_id'), table_name='historical_prices')
    op.drop_table('historical_prices')
    op.drop_index(op.f('ix_historical_financials_company_id'), table_name='historical_financials')
    op.drop_table('historical_financials')
    op.drop_index(op.f('ix_financial_facts_company_id'), table_name='financial_facts')
    op.drop_table('financial_facts')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_company_id'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_consensus_snapshots_ticker'), table_name='consensus_snapshots')
    op.drop_index(op.f('ix_consensus_snapshots_date'), table_name='consensus_snapshots')
    op.drop_index(op.f('ix_consensus_snapshots_company_id'), table_name='consensus_snapshots')
    op.drop_table('consensus_snapshots')
    op.drop_index(op.f('ix_company_insights_company_id'), table_name='company_insights')
    op.drop_table('company_insights')
    op.drop_index(op.f('ix_auth_events_user_id'), table_name='auth_events')
    op.drop_index(op.f('ix_auth_events_email'), table_name='auth_events')
    op.drop_table('auth_events')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_alpha_snapshots_ticker'), table_name='alpha_snapshots')
    op.drop_index(op.f('ix_alpha_snapshots_date'), table_name='alpha_snapshots')
    op.drop_index(op.f('ix_alpha_snapshots_company_id'), table_name='alpha_snapshots')
    op.drop_table('alpha_snapshots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_saved_screens_user_key'), table_name='saved_screens')
    op.drop_table('saved_screens')
    op.drop_index(op.f('ix_saved_scenarios_user_key'), table_name='saved_scenarios')
    op.drop_index(op.f('ix_saved_scenarios_ticker'), table_name='saved_scenarios')
    op.drop_table('saved_scenarios')
    op.drop_index(op.f('ix_kv_store_key'), table_name='kv_store')
    op.drop_table('kv_store')
    op.drop_index(op.f('ix_engine_calls_ticker'), table_name='engine_calls')
    op.drop_index(op.f('ix_engine_calls_date'), table_name='engine_calls')
    op.drop_table('engine_calls')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_template_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_bse_scrip_code'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_api_usage_month'), table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
