#!/usr/bin/env bash
# Regenerate the frontend parity fixtures from THIS backend, verify both
# harnesses, and auto-commit + push the fixture update in the frontend repo.
#
# Invoked automatically by the pre-push hook (scripts/hooks/pre-push) whenever
# app/engines.py, app/derive.py or app/sector_params.py are in the outgoing
# push — so the cross-repo fixture step can never be forgotten. A harness
# mismatch exits non-zero, which BLOCKS the backend push: exactly the guard.
set -euo pipefail

BACKEND_DIR="$(cd "$(dirname "$0")/.." && pwd)"
FRONTEND_DIR="${FRONTEND_DIR:-$HOME/equity-terminal}"
PY="$BACKEND_DIR/venv313/bin/python"
[ -x "$PY" ] || PY=python3

if [ ! -d "$FRONTEND_DIR/tests" ]; then
  echo "sync_parity_fixtures: frontend repo not found at $FRONTEND_DIR (set FRONTEND_DIR)" >&2
  exit 1
fi

echo "· regenerating parity fixtures → $FRONTEND_DIR/tests"
"$PY" "$BACKEND_DIR/tests/gen_parity_cases.py" "$FRONTEND_DIR/tests/parityCases.json"
"$PY" "$BACKEND_DIR/tests/gen_derive_cases.py" "$FRONTEND_DIR/tests/deriveCases.json"

echo "· verifying harnesses against the regenerated fixtures"
(cd "$FRONTEND_DIR" && node tests/engineParity.mjs && node tests/deriveParity.mjs)

if git -C "$FRONTEND_DIR" diff --quiet -- tests/parityCases.json tests/deriveCases.json; then
  echo "· fixtures unchanged — nothing to commit"
  exit 0
fi

sha="$(git -C "$BACKEND_DIR" rev-parse --short HEAD)"
git -C "$FRONTEND_DIR" add tests/parityCases.json tests/deriveCases.json
git -C "$FRONTEND_DIR" commit -m "Parity fixtures: regenerate for backend ${sha}

Auto-generated by scripts/sync_parity_fixtures.sh (backend pre-push hook) —
keeps the committed engine/derive fixtures bit-identical to the backend so
frontend CI's 60/60 + 48/48 gates stay meaningful.

Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>"
git -C "$FRONTEND_DIR" push origin main
echo "· fixtures regenerated, committed and pushed (frontend)"
